# Generated by Django 4.1.2 on 2024-06-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_user', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=20, unique=True)),
                ('contasena', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(blank=True, max_length=20, null=True)),
                ('genero', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
    ]
