# Generated by Django 4.1.2 on 2024-06-25 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=20, null=True, verbose_name='Apellido Materno')),
                ('genero', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='correo')),
                ('mas18', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='indie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('categoria', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='registro_colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, unique=True, verbose_name='usuario')),
                ('contasena', models.CharField(max_length=12)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.colaboradores')),
            ],
        ),
    ]
