# Generated by Django 4.1.2 on 2024-06-28 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indie',
            name='id',
        ),
        migrations.RemoveField(
            model_name='registro_colaborador',
            name='id',
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='id_user',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indie',
            name='id_indie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.registro_colaborador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registro_colaborador',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.colaboradores'),
        ),
    ]
