# Generated by Django 4.1.2 on 2024-06-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_indie_id_remove_registro_colaborador_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_colaborador',
            name='id_indie',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
